[env:airm2m_core_esp32c3]
platform = espressif32
board = airm2m_core_esp32c3
framework = arduino

monitor_speed = 115200
; ✅ 优化1：保留原有的异常解码器，新增 time 过滤器给日志加时间戳
monitor_filters = esp32_exception_decoder, time

lib_deps = 
    fastled/FastLED @ ^3.7.0
    mathertel/OneButton @ ^2.5.0
    h2zero/NimBLE-Arduino @ ^1.4.1

; ✅ 优化2：新增这行，开启 Debug 构建，消除启动时的 "Please build in debug" 提示
build_type = debug

build_flags = 
    -D CORE_DEBUG_LEVEL=0
    -O2